config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: fix/updatego
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/edubadges/edubadges-server:
      branch: develop
      repo: https://github.com/edubadges/edubadges-server
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/edubadges/edubadges-server git:
        commands:
        - /usr/bin/env sh .sqa/script.jade_resourceful_raven.sh
        container: qc.acc_echelon_pensive_barracuda
  QC.Doc:
    repos:
      github.com/edubadges/edubadges-server find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.linen_dedicated_horse.sh
        container: qc.doc_avocado_grateful_dragonfly
      github.com/edubadges/edubadges-server git:
        commands:
        - /usr/bin/env sh .sqa/script.espresso_authentic_antelope.sh
        container: qc.doc_azure_peppy_boar
      github.com/edubadges/edubadges-server markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.ruby_feisty_alligator.sh
        container: qc.doc_sepia_shrewd_axolotl
  QC.Lic:
    repos:
      github.com/edubadges/edubadges-server licensee:
        commands:
        - /usr/bin/env sh .sqa/script.cream_mindful_rattlesnake.sh
        container: qc.lic_mist_affectionate_orca
  QC.Sec:
    repos:
      github.com/edubadges/edubadges-server bandit:
        commands:
        - /usr/bin/env sh .sqa/script.plum_candid_jellyfish.sh
        container: qc.sec_gray_feisty_dormouse
  QC.Sty:
    repos:
      github.com/edubadges/edubadges-server flake8:
        commands:
        - /usr/bin/env sh .sqa/script.dahlia_tenacious_crane.sh
        container: qc.sty_jasmine_zealous_spren
      github.com/edubadges/edubadges-server hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.avocado_realistic_boar.sh
        container: qc.sty_fog_mischievous_gerbil
      github.com/edubadges/edubadges-server jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.arctic_clever_seahorse.sh
        container: qc.sty_alabaster_unique_rhinoceros
  QC.Uni:
    repos:
      github.com/edubadges/edubadges-server pytest:
        commands:
        - /usr/bin/env sh .sqa/script.horizon_foolish_eagle.sh
        container: qc.uni_sapphire_fierce_spren
  QC.Ver:
    repos:
      github.com/edubadges/edubadges-server get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.chili_graceful_boa.sh
        container: qc.ver_raspberry_honest_condor
timeout: 5400
